### ISSUE TITLE
GammaNS(15)

### ISSUE THREAD

**Issue by jvoight** [assaferan/ModFrmGL2#1]
Alas, I couldn't get GammaNS to work with composite N.  If this isn't implemented yet, it should say so in the doc.  If it is supposed to work, I get

> GammaNSplus(15);
[...]
Runtime error in 'GammaNS' : u must be a nonsquare mod every prime dividing N
> GammaNSplus(15, Integers(15)!2);
[...]
Runtime error in 'GF': Argument 1 (15) is not a prime power

**Comment by assaferan** [comment]
Sorry.
Indeed, it hasn't been implemented yet. (for composite N in general)
However, now it is.
