### ISSUE TITLE
GammaNSplus(49)

### ISSUE THREAD

**Issue by jvoight** [assaferan/ModFrmGL2#3]
Should this work?

```
> GammaNSplus(49);

GammaNSplus(
    N: 49
)
GammaNS(
    N: 49
)
In file "/Users/jvoight/Dropbox (John Voight)/github/ModFrmGL2/ModFrmGL2/GrpPSL\
2/GrpPSL2/creation.m", line 285, column 22:
>>        return GammaNS(N, x^2 - u);
                        ^
Runtime error in 'GammaNS': N for which ZZ[alpha] is not a maximal order 
                         are not supported at the moment
```

**Comment by jvoight** [comment]
It seems to work OK with 
```
> GammaNSplus(49, 3);
```

**Comment by assaferan** [comment]
Oh, I remember that - at the time there was some issue with implementing the order in magma.
There was some problem when it is not maximal, that for some reason magma couldn’t do.
I will look into it, but am more concerned at the moment with the q-expansions.
This boils down to the linear algebra we were talking about in the beginning of the year (matching the constants between eigenvectors and eigenforms).
For some reason, it takes me a long while to get it to work - meanwhile I only got it to work on some small examples.

If you really need this one, even though the q-expansions are wrong, I can probably fix it first and then go back to the above, so let me know.

**Comment by jvoight** [comment]
No, this isn't a priority--I agree it's more important to sort out what's happening with q-expansions.

**Comment by assaferan** [comment]
This works now.

**Comment by assaferan** [comment]
This should have been resolved two years ago, but hopefully also now in PR #23
